# Generated by Django 5.2.4 on 2025-08-05 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('slot', models.PositiveSmallIntegerField(default=0)),
                ('tag', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('Amp', 'Corriente'), ('Temp', 'Temperatura')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Lectura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField(null=True)),
                ('timetamp', models.DateField(auto_now_add=True)),
                ('vdf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lectura', to='vdf_monitor.vdf')),
            ],
        ),
    ]
