# Generated by Django 5.2.4 on 2025-08-05 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vdf_monitor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lectura',
            name='vdf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturas', to='vdf_monitor.vdf'),
        ),
    ]
