# Generated by Django 5.2.4 on 2025-08-05 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vdf_monitor', '0002_alter_lectura_vdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='vdf',
            name='descripcion',
            field=models.TextField(blank=True, verbose_name='Descripcion'),
        ),
        migrations.AddField(
            model_name='vdf',
            name='nombre',
            field=models.CharField(blank=True, help_text='Nombre Fisico/ubicacion del VDF', max_length=100, verbose_name='nombre'),
        ),
    ]
