# Generated by Django 5.2.4 on 2025-08-06 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vdf_monitor', '0003_vdf_descripcion_vdf_nombre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lectura',
            old_name='timetamp',
            new_name='timestamp',
        ),
    ]
