# Generated by Django 5.2.4 on 2025-08-11 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vdf_monitor', '0004_rename_timetamp_lectura_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='vdf',
            name='area',
            field=models.CharField(blank=True, help_text='E.G. Construccion', max_length=50, verbose_name='Área'),
        ),
        migrations.AddField(
            model_name='vdf',
            name='division',
            field=models.CharField(blank=True, help_text='E.g. Divicion A, Division B', max_length=50, verbose_name='División'),
        ),
    ]
