# Generated by Django 5.2.4 on 2025-08-11 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vdf_monitor', '0005_vdf_area_vdf_division'),
    ]

    operations = [
        migrations.AddField(
            model_name='vdf',
            name='zone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Zona'),
        ),
        migrations.AlterField(
            model_name='lectura',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='vdf',
            name='area',
            field=models.CharField(blank=True, max_length=50, verbose_name='Área'),
        ),
        migrations.AlterField(
            model_name='vdf',
            name='descripcion',
            field=models.TextField(blank=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='vdf',
            name='division',
            field=models.CharField(blank=True, max_length=50, verbose_name='División'),
        ),
        migrations.AlterField(
            model_name='vdf',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='vdf',
            name='tag',
            field=models.CharField(max_length=150),
        ),
    ]
