# Generated by Django 5.2.4 on 2025-08-11 20:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vdf_monitor', '0006_vdf_zone_alter_lectura_timestamp_alter_vdf_area_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lectura',
            name='estado',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='lectura',
            name='timestamp',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='lectura',
            name='valor',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lectura',
            name='vdf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vdf_monitor.vdf'),
        ),
    ]
