# Generated by Django 5.2.5 on 2025-08-13 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vdf_monitor', '0007_lectura_estado_alter_lectura_timestamp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterModelOptions(
            name='lectura',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterField(
            model_name='lectura',
            name='vdf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturas', to='vdf_monitor.vdf'),
        ),
        migrations.AlterField(
            model_name='vdf',
            name='area',
            field=models.CharField(blank=True, max_length=50, verbose_name='Área (texto)'),
        ),
        migrations.AlterField(
            model_name='vdf',
            name='division',
            field=models.CharField(blank=True, max_length=50, verbose_name='División (texto)'),
        ),
        migrations.AlterField(
            model_name='vdf',
            name='zone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Zona (texto)'),
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='areas', to='vdf_monitor.division')),
            ],
            options={
                'ordering': ['division__nombre', 'nombre'],
                'unique_together': {('division', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='zonas', to='vdf_monitor.area')),
            ],
            options={
                'ordering': ['area__division__nombre', 'area__nombre', 'nombre'],
                'unique_together': {('area', 'nombre')},
            },
        ),
        migrations.AddField(
            model_name='vdf',
            name='zona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vdfs', to='vdf_monitor.zona'),
        ),
    ]
