# Generated by Django 5.2.5 on 2025-10-24 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vdf_monitor', '0008_division_alter_lectura_options_alter_lectura_vdf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lectura',
            name='estado',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='lectura',
            name='vdf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lecturas_legacy', to='vdf_monitor.vdf'),
        ),
        migrations.AlterField(
            model_name='vdf',
            name='area',
            field=models.CharField(blank=True, max_length=50, verbose_name='Área (texto - legado)'),
        ),
        migrations.AlterField(
            model_name='vdf',
            name='division',
            field=models.CharField(blank=True, max_length=50, verbose_name='División (texto - legado)'),
        ),
        migrations.AlterField(
            model_name='vdf',
            name='tag',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Tag (legado)'),
        ),
        migrations.AlterField(
            model_name='vdf',
            name='tipo',
            field=models.CharField(blank=True, choices=[('Amp', 'Corriente'), ('Temp', 'Temperatura')], default='', max_length=10, verbose_name='Tipo (legado)'),
        ),
        migrations.AlterField(
            model_name='vdf',
            name='zone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Zona (texto - legado)'),
        ),
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.CharField(choices=[('amp', 'Corriente (A)'), ('temp', 'Temperatura (°C)')], db_index=True, max_length=16)),
                ('tag', models.CharField(max_length=200, unique=True)),
                ('vdf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='vdf_monitor.vdf')),
            ],
        ),
        migrations.AddField(
            model_name='lectura',
            name='signal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lecturas', to='vdf_monitor.signal'),
        ),
        migrations.AddIndex(
            model_name='lectura',
            index=models.Index(fields=['signal', '-timestamp'], name='vdf_monitor_signal__e73297_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='signal',
            unique_together={('vdf', 'metric')},
        ),
    ]
