# Generated by Django 5.2.5 on 2025-10-24 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vdf_monitor', '0011_make_signal_nonnull'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='signal',
            options={'ordering': ['vdf_id', 'metric', 'tag']},
        ),
        migrations.AlterUniqueTogether(
            name='signal',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='lectura',
            name='vdf',
        ),
    ]
