# Generated by Django 5.2.5 on 2025-11-04 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vdf_monitor', '0012_alter_signal_options_alter_signal_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signal',
            name='tag',
            field=models.CharField(max_length=200),
        ),
        migrations.AddConstraint(
            model_name='signal',
            constraint=models.UniqueConstraint(fields=('vdf', 'tag'), name='uq_signal_tag_por_vdf'),
        ),
    ]
